# -*- coding: utf-8 -*-
"""01_fraud_anomaly_detection_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGDSSzcZKisYUgguEQ8PEPfcHduN8-kN

# Fraud Detection & Transaction Anomaly Analysis
## 01 — Python Data Exploration and EDA

This notebook extends the SQL transaction-risk framework through exploratory data analysis, behavioural feature preparation and unsupervised anomaly detection using Isolation Forest.

The SQL layer performs the core data modelling, customer behavioural baseline construction, risk feature engineering and transparent rule-based transaction scoring.

Python is used as a complementary analytical layer to:

- validate the SQL-generated dataset;
- explore transaction and risk-feature distributions;
- investigate behavioural patterns;
- prepare the data for unsupervised anomaly detection.

> The source dataset does not contain confirmed fraud labels. Therefore, the analysis focuses on transaction-risk patterns and statistical anomalies rather than confirmed fraud prediction.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# Exploratory Data Analysis (EDA)

Load the SQL Analytics Dataset
"""

df = pd.read_csv("/content/fraud_analytics_dataset.csv")

"""## 1. Dataset Overview & Validation"""

# Preview the first records
df.head()

# Dataset structure and data types
df.info()

# Dataset dimensions
print(f"Total Rows: {df.shape[0]:,}")
print(f"Total Columns: {df.shape[1]}")

"""The dataset contains **31,465 transaction records and 36 analytical fields**."""

# Duplicate rows
print(f"Exact duplicate rows: {df.duplicated().sum():,}")

# Duplicate transaction IDs
print(
    f"Duplicate SalesOrderID values: "
    f"{df['SalesOrderID'].duplicated().sum():,}"
)

# Missing values summary
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().mean() * 100).round(2)
})

missing_summary = (
    missing_summary[missing_summary["missing_count"] > 0]
    .sort_values("missing_count", ascending=False)
)

missing_summary

"""## 2. Descriptive Statistics"""

numeric_analysis_columns = [
    "order_value",
    "days_since_previous_order",
    "prior_order_count",
    "prior_avg_order_value",
    "amount_vs_customer_avg",
    "transaction_risk_score"
]

df[numeric_analysis_columns].describe().round(2)

"""## 3. Categorical Variables"""

df["risk_level"].value_counts(normalize=True)

df["risk_reason"].value_counts().head(10)

df["OnlineOrderFlag"].value_counts(normalize=True)

"""## 4. Transaction Value Analysis

This section explores the distribution of transaction values to identify skewness, extreme observations and potential high-value anomalies.
"""

df["order_value"].describe(
    percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
).round(2)

plt.figure(figsize=(10, 5))

plt.hist(
    df["order_value"],
    bins=50
)

plt.title("Distribution of Transaction Values")
plt.xlabel("Order Value")
plt.ylabel("Number of Transactions")

plt.show()

df["log_order_value"] = np.log1p(df["order_value"])

plt.figure(figsize=(10, 5))

plt.hist(
    df["log_order_value"],
    bins=50
)

plt.title("Distribution of Log-Transformed Transaction Values")
plt.xlabel("Log-Transformed Order Value")
plt.ylabel("Number of Transactions")

plt.show()

"""## 5. Customer Behavioural Deviation

Transaction values are evaluated relative to each customer`s historical purchasing behaviour.

The `amount_vs_customer_avg` feature measures how large the current transaction is compared with the customer's previous average transaction value.
"""

df["amount_vs_customer_avg"].describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
).round(2)

amount_ratio_plot = df[
    df["amount_vs_customer_avg"].between(
        0,
        df["amount_vs_customer_avg"].quantile(0.99)
    )
]["amount_vs_customer_avg"]

plt.figure(figsize=(10, 5))

plt.hist(
    amount_ratio_plot.dropna(),
    bins=50
)

plt.axvline(
    3,
    linestyle="--",
    label="SQL amount-spike threshold (3x)"
)

plt.title("Transaction Value Relative to Customer Historical Average")
plt.xlabel("Current Order / Historical Customer Average")
plt.ylabel("Number of Transactions")
plt.legend()

plt.show()

"""## 6. Transaction Velocity Analysis

The time between consecutive customer transactions is analysed to identify unusually rapid purchasing activity.
"""

df["days_since_previous_order"].describe(
    percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
).round(2)

velocity_segments = pd.cut(
    df["days_since_previous_order"],
    bins=[-1, 0, 7, 30, 90, float("inf")],
    labels=[
        "Same day",
        "1-7 days",
        "8-30 days",
        "31-90 days",
        "More than 90 days"
    ]
)

velocity_segments.value_counts().reindex([
    "Same day",
    "1-7 days",
    "8-30 days",
    "31-90 days",
    "More than 90 days"
])

"""## 7. Risk Indicator Analysis

The frequency of each SQL-generated risk indicator is compared to understand which transaction-risk signals occur most frequently.
"""

risk_flags = [
    "same_day_repeat_flag",
    "rapid_repeat_flag",
    "amount_spike_flag",
    "city_mismatch_flag",
    "state_mismatch_flag"
]

risk_flag_counts = df[risk_flags].sum().sort_values(ascending=False)

risk_flag_counts

plt.figure(figsize=(9, 5))

risk_flag_counts.plot(kind="bar")

plt.title("Frequency of Transaction Risk Indicators")
plt.xlabel("Risk Indicator")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)

plt.show()

"""## 8. SQL Risk Score Analysis

The distribution of the rule-based SQL risk score is analysed to understand how transactions are prioritised across different levels of investigation risk.
"""

risk_score_distribution = (
    df["transaction_risk_score"]
    .value_counts()
    .sort_index()
)

risk_score_distribution

plt.figure(figsize=(8, 5))

risk_score_distribution.plot(kind="bar")

plt.title("Distribution of Transaction Risk Scores")
plt.xlabel("Transaction Risk Score")
plt.ylabel("Number of Transactions")

plt.show()

risk_level_distribution = (
    df["risk_level"]
    .value_counts()
    .reindex(["High", "Medium", "Low"])
)

risk_level_distribution

"""## 9. Transaction Behaviour by Risk Level

Transaction characteristics are compared across SQL risk levels to understand how behavioural and value-based patterns differ between low-, medium- and high-priority transactions.
"""

risk_level_summary = (
    df.groupby("risk_level")
      .agg(
          transaction_count=("SalesOrderID", "count"),
          avg_order_value=("order_value", "mean"),
          median_order_value=("order_value", "median"),
          avg_days_since_previous_order=("days_since_previous_order", "mean"),
          avg_amount_vs_customer_avg=("amount_vs_customer_avg", "mean"),
          avg_risk_score=("transaction_risk_score", "mean")
      )
      .round(2)
)

risk_level_summary

"""## 10. High-Priority Transaction Review

The transactions classified as High risk by the SQL framework are reviewed individually to understand which combinations of behavioural signals drove their prioritisation.
"""

high_risk_transactions = (
    df[df["risk_level"] == "High"]
    .sort_values(
        by=["transaction_risk_score", "amount_vs_customer_avg"],
        ascending=[False, False]
    )
)

high_risk_transactions[
    [
        "SalesOrderID",
        "CustomerID",
        "OrderDate",
        "order_value",
        "days_since_previous_order",
        "prior_order_count",
        "prior_avg_order_value",
        "amount_vs_customer_avg",
        "transaction_risk_score",
        "risk_reason"
    ]
]

"""### EDA Findings

The exploratory analysis shows that the SQL risk framework identifies a relatively small subset of transactions with unusual behavioural characteristics.

High-priority transactions are not necessarily the transactions with the highest absolute values. Instead, many are characterised by a combination of:

- unusually short time intervals between consecutive purchases;
- transaction values substantially above the customer's historical average;
- multiple simultaneous behavioural risk signals.

The highest-priority transaction combines same-day repeat activity with an amount spike, resulting in the maximum observed SQL risk score.

These findings support the use of customer-specific behavioural baselines rather than relying exclusively on global transaction-value thresholds.

# Data Preprocessing for Anomaly Detection

The preprocessing stage prepares the analytical dataset for unsupervised anomaly detection.

Unlike conventional predictive modelling, unusual but valid observations are deliberately preserved because they may represent the anomalies the model is intended to detect.

SQL-generated risk scores, risk classifications and rule-based indicators are excluded from the model features to allow an independent comparison between the SQL risk framework and the Python anomaly-detection model.
"""

# Create modelling copy
df_model = df.copy()

print(f"Modelling dataset: {df_model.shape[0]:,} rows × {df_model.shape[1]} columns")

df_model

"""## 1. Feature Selection

The anomaly-detection model is intentionally built using behavioural transaction variables rather than the SQL-generated risk score or rule-based risk flags.

This prevents information leakage and enables an independent comparison between rule-based SQL risk detection and data-driven anomaly detection.
"""

# Select model features
model_features = [
    "order_value",
    "days_since_previous_order",
    "prior_order_count",
    "prior_avg_order_value",
    "amount_vs_customer_avg",
    "OnlineOrderFlag"
]

# Create feature dataset
X = df_model[model_features].copy()

X.head()

# Check missing values
X.isnull().sum()

X.dropna()

"""### Historical Behaviour Availability

Missing values in the historical behaviour features are expected rather than data-quality errors.

For a customer's first recorded transaction, no previous order or historical spending baseline exists. Since the anomaly-detection model relies on customer behavioural history, transactions without prior history are excluded from the modelling sample rather than artificially imputed.

The original analytical dataset remains unchanged.
"""

# Identify first orders
first_orders = X["prior_order_count"] == 0

print(f"First transactions: {first_orders.sum():,}")

# Filter historical transactions
X_model = X.loc[X["prior_order_count"] > 0].copy()

print(f"Model rows: {X_model.shape[0]:,}")

# Recheck missing values
X_model.isnull().sum()

"""## 2. Feature Transformation

Highly skewed numerical variables are log-transformed to reduce the influence of extreme magnitudes while preserving unusual observations.

Extreme transactions are not removed, as they may represent the anomalies the model is intended to identify.
"""

# Create transformed dataset
X_processed = X_model.copy()

# Log-transform features
log_features = [
    "order_value",
    "days_since_previous_order",
    "prior_avg_order_value",
    "amount_vs_customer_avg"
]

for column in log_features:
    X_processed[column] = np.log1p(X_processed[column])

# Review transformed data
X_processed.describe().round(2)

"""## 3. Feature Scaling

Numerical features are standardised before anomaly detection so that differences in measurement scale do not disproportionately influence the modelling process.
"""

# Import scaler
from sklearn.preprocessing import StandardScaler

# Scale model features
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_processed)
X_scaled

# Restore feature names
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X_processed.columns,
    index=X_processed.index
)

X_scaled.head()

# Validate scaled features
X_scaled.agg(["mean", "std"]).round(2)

"""# Unsupervised Anomaly Detection

## 4. Isolation Forest

Isolation Forest is applied to identify transactions whose behavioural characteristics differ substantially from the broader transaction population.

The model is trained only on behavioural transaction features and does not use the SQL-generated risk score, risk level or rule-based risk indicators. This allows the model to provide an independent anomaly-detection perspective.
"""

# Import model
from sklearn.ensemble import IsolationForest

# Create Isolation Forest
isolation_forest = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42
)

# Train model
isolation_forest.fit(X_scaled)

# Predict anomalies
anomaly_prediction = isolation_forest.predict(X_scaled)

# Calculate anomaly scores
anomaly_score = -isolation_forest.decision_function(X_scaled)

"""## 5. Model Results

The Isolation Forest predictions and anomaly scores are mapped back to the original transaction records while preserving the original dataset index.
"""

# Create results dataset
model_results = df_model.loc[X_model.index].copy()

# Add model predictions
model_results["anomaly_prediction"] = anomaly_prediction
model_results["anomaly_score"] = anomaly_score

# Create anomaly flag
model_results["anomaly_flag"] = (
    model_results["anomaly_prediction"] == -1
).astype(int)

# Count model anomalies
model_results["anomaly_flag"].value_counts()

# Calculate anomaly rate
model_results["anomaly_flag"].value_counts(
    normalize=True
).mul(100).round(2)

# Review top anomalies
top_anomalies = (
    model_results[
        model_results["anomaly_flag"] == 1
    ]
    .sort_values(
        "anomaly_score",
        ascending=False
    )
)

top_anomalies[
    [
        "SalesOrderID",
        "CustomerID",
        "OrderDate",
        "order_value",
        "days_since_previous_order",
        "prior_order_count",
        "prior_avg_order_value",
        "amount_vs_customer_avg",
        "anomaly_score"
    ]
].head(10)

model_results["anomaly_flag"].value_counts()

model_results["anomaly_flag"].value_counts(
    normalize=True
).mul(100).round(2)

"""### Automatic Isolation Forest Threshold

Using the default automatic threshold, Isolation Forest classified 2,907 transactions (23.55% of the modelling sample) as anomalous.

This threshold is considered too broad for transaction-investigation prioritisation. Therefore, the binary prediction is retained for reference, while the continuous anomaly score is used as the primary model output for ranking unusual transactions.

## 6. Anomaly Score Analysis

The continuous Isolation Forest anomaly score is analysed instead of relying exclusively on the model's automatic binary classification.

Higher anomaly scores represent transactions that are more unusual relative to the behavioural patterns observed in the modelling population.
"""

# Review anomaly scores
model_results["anomaly_score"].describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
).round(4)

# Plot anomaly scores
plt.figure(figsize=(10, 5))

plt.hist(
    model_results["anomaly_score"],
    bins=50
)

plt.title("Distribution of Isolation Forest Anomaly Scores")
plt.xlabel("Anomaly Score")
plt.ylabel("Number of Transactions")

plt.show()

# Create anomaly percentile
model_results["anomaly_percentile"] = (
    model_results["anomaly_score"]
    .rank(pct=True)
)

# Create review thresholds
model_results["top_1pct_anomaly"] = (
    model_results["anomaly_percentile"] >= 0.99
).astype(int)

model_results["top_5pct_anomaly"] = (
    model_results["anomaly_percentile"] >= 0.95
).astype(int)

model_results["top_10pct_anomaly"] = (
    model_results["anomaly_percentile"] >= 0.90
).astype(int)

# Count priority groups
print(
    "Top 1%:",
    model_results["top_1pct_anomaly"].sum()
)

print(
    "Top 5%:",
    model_results["top_5pct_anomaly"].sum()
)

print(
    "Top 10%:",
    model_results["top_10pct_anomaly"].sum()
)

"""## 7. SQL vs Python Risk Comparison

The independently generated Python anomaly scores are compared with the SQL rule-based risk classifications.

This comparison evaluates whether transactions prioritised through transparent behavioural rules also appear unusual from an unsupervised machine-learning perspective.
"""

# Compare risk levels
pd.crosstab(
    model_results["risk_level"],
    model_results["anomaly_flag"]
)

# Compare top anomalies
sql_python_comparison = (
    model_results
    .groupby("risk_level")
    .agg(
        transactions=("SalesOrderID", "count"),
        avg_anomaly_score=("anomaly_score", "mean"),
        top_1pct=("top_1pct_anomaly", "sum"),
        top_5pct=("top_5pct_anomaly", "sum"),
        top_10pct=("top_10pct_anomaly", "sum")
    )
    .round(4)
)

sql_python_comparison

"""### Cross-Method Agreement

The comparison shows strong alignment between the independently developed SQL risk framework and the Isolation Forest anomaly model.

Transactions assigned higher SQL risk levels also exhibit substantially higher Python anomaly scores and are disproportionately represented among the most unusual transactions identified by the model.
"""

# Calculate overlap rates
comparison_rates = sql_python_comparison.copy()

comparison_rates["top_1pct_rate"] = (
    comparison_rates["top_1pct"] /
    comparison_rates["transactions"] * 100
).round(2)

comparison_rates["top_5pct_rate"] = (
    comparison_rates["top_5pct"] /
    comparison_rates["transactions"] * 100
).round(2)

comparison_rates["top_10pct_rate"] = (
    comparison_rates["top_10pct"] /
    comparison_rates["transactions"] * 100
).round(2)

comparison_rates[
    [
        "avg_anomaly_score",
        "top_1pct_rate",
        "top_5pct_rate",
        "top_10pct_rate"
    ]
]

# Plot overlap rates
comparison_rates[
    [
        "top_1pct_rate",
        "top_5pct_rate",
        "top_10pct_rate"
    ]
].plot(
    kind="bar",
    figsize=(10, 5)
)

plt.title("Python Anomaly Concentration by SQL Risk Level")
plt.xlabel("SQL Risk Level")
plt.ylabel("Transactions in Anomaly Group (%)")
plt.xticks(rotation=0)
plt.legend(
    ["Top 1%", "Top 5%", "Top 10%"]
)

plt.show()

# Review model-only anomalies
python_only_anomalies = (
    model_results[
        (model_results["risk_level"] == "Low") &
        (model_results["top_1pct_anomaly"] == 1)
    ]
    .sort_values(
        "anomaly_score",
        ascending=False
    )
)

python_only_anomalies[
    [
        "SalesOrderID",
        "CustomerID",
        "OrderDate",
        "order_value",
        "days_since_previous_order",
        "prior_order_count",
        "prior_avg_order_value",
        "amount_vs_customer_avg",
        "anomaly_score",
        "risk_reason"
    ]
].head(10)

# Review SQL high risk
high_risk_comparison = (
    model_results[
        model_results["risk_level"] == "High"
    ]
    .sort_values(
        "anomaly_score",
        ascending=False
    )
)

high_risk_comparison[
    [
        "SalesOrderID",
        "CustomerID",
        "order_value",
        "days_since_previous_order",
        "amount_vs_customer_avg",
        "transaction_risk_score",
        "anomaly_score",
        "anomaly_percentile",
        "risk_reason"
    ]
]

"""## 8. Cross-Method Agreement

The SQL rule-based risk framework and the Isolation Forest model are compared to evaluate whether independently identified risk patterns converge on the same transactions.

Because the Python model was trained without SQL-generated risk scores, risk levels or rule-based flags, this comparison provides an independent validation of the behavioural risk framework.
"""

# Calculate overlap rates
comparison_rates = sql_python_comparison.copy()

comparison_rates["top_1pct_rate"] = (
    comparison_rates["top_1pct"]
    / comparison_rates["transactions"] * 100
).round(2)

comparison_rates["top_5pct_rate"] = (
    comparison_rates["top_5pct"]
    / comparison_rates["transactions"] * 100
).round(2)

comparison_rates["top_10pct_rate"] = (
    comparison_rates["top_10pct"]
    / comparison_rates["transactions"] * 100
).round(2)

comparison_rates[
    [
        "avg_anomaly_score",
        "top_1pct_rate",
        "top_5pct_rate",
        "top_10pct_rate"
    ]
]

"""### Key Finding

- A strong relationship emerges between the two independent approaches.

- All SQL High-risk transactions fall within the top 10% of Isolation Forest anomalies, while 80% are within the top 5% and 20% within the top 1%.

- Medium-risk transactions also show substantially greater anomaly concentration than Low-risk transactions.

- This suggests that the customer-specific behavioural rules developed in SQL capture patterns that are independently recognised as unusual by the unsupervised machine-learning model.
"""

# Plot overlap rates
comparison_rates[
    [
        "top_1pct_rate",
        "top_5pct_rate",
        "top_10pct_rate"
    ]
].plot(
    kind="bar",
    figsize=(10, 5)
)

plt.title("Python Anomaly Concentration by SQL Risk Level")
plt.xlabel("SQL Risk Level")
plt.ylabel("Transactions in Anomaly Group (%)")
plt.xticks(rotation=0)
plt.legend(["Top 1%", "Top 5%", "Top 10%"])

plt.show()

"""## 9. Python-Only Anomaly Investigation

Transactions classified as Low risk by the SQL framework but ranked within the top 1% of Isolation Forest anomalies are examined separately.

These observations are particularly relevant because they may reveal unusual multivariate patterns that do not exceed any individual SQL rule threshold.
"""

# Identify model-only anomalies
python_only_anomalies = (
    model_results[
        (model_results["risk_level"] == "Low")
        & (model_results["top_1pct_anomaly"] == 1)
    ]
    .sort_values(
        "anomaly_score",
        ascending=False
    )
)

print(
    f"SQL Low-risk transactions in Python top 1%: "
    f"{len(python_only_anomalies):,}"
)

# Review model-only anomalies
python_only_anomalies[
    [
        "SalesOrderID",
        "CustomerID",
        "OrderDate",
        "order_value",
        "days_since_previous_order",
        "prior_order_count",
        "prior_avg_order_value",
        "amount_vs_customer_avg",
        "anomaly_score",
        "risk_reason"
    ]
].head(10)

"""### Behavioural Profile Comparison

Python-only anomalies are compared with the broader SQL Low-risk population to identify which behavioural characteristics make them statistically unusual.
"""

# Compare behavioural profiles
low_risk_normal = model_results[
    (model_results["risk_level"] == "Low")
    & (model_results["top_1pct_anomaly"] == 0)
]

profile_comparison = pd.DataFrame({
    "Python Top 1%": python_only_anomalies[
        [
            "order_value",
            "days_since_previous_order",
            "prior_order_count",
            "prior_avg_order_value",
            "amount_vs_customer_avg"
        ]
    ].median(),

    "Other Low Risk": low_risk_normal[
        [
            "order_value",
            "days_since_previous_order",
            "prior_order_count",
            "prior_avg_order_value",
            "amount_vs_customer_avg"
        ]
    ].median()
}).round(2)

profile_comparison

"""## 10. High-Risk Transaction Validation

The ten transactions classified as High risk by the SQL framework are reviewed alongside their Python anomaly scores and percentiles.
"""

# Review SQL high risk
high_risk_comparison = (
    model_results[
        model_results["risk_level"] == "High"
    ]
    .sort_values(
        "anomaly_score",
        ascending=False
    )
)

high_risk_comparison[
    [
        "SalesOrderID",
        "CustomerID",
        "order_value",
        "days_since_previous_order",
        "prior_order_count",
        "prior_avg_order_value",
        "amount_vs_customer_avg",
        "transaction_risk_score",
        "anomaly_score",
        "anomaly_percentile",
        "risk_reason"
    ]
]

"""## Model Interpretation

- The SQL and Python approaches provide complementary perspectives on transaction risk.

- The SQL framework offers transparent and directly interpretable investigation rules based on transaction velocity, customer spending deviations and geographic inconsistencies.

- Isolation Forest independently confirms that the highest SQL-risk transactions exhibit statistically unusual behavioural profiles, while also identifying additional anomalies that do not exceed any individual SQL threshold.

- Rather than treating the machine-learning model as a fraud classifier, the anomaly score is used as an additional prioritisation signal that can surface unusual transaction combinations for further investigation.

### High-Risk Validation Findings

- The SQL High-risk transactions show strong alignment with the independently generated Isolation Forest anomaly scores.

- All ten High-risk transactions fall within the top 10% of Python anomalies, eight fall within the top 5%, and two fall within the top 1%.

- The strongest cases combine unusually rapid repeat purchasing with transaction values substantially above the customer's historical average.

- This convergence suggests that the transparent SQL behavioural rules are capturing transaction patterns that are also statistically unusual when evaluated through an unsupervised multivariate model.

## 11. Python-Only Anomaly Investigation

Transactions classified as Low risk by the SQL framework but ranked within the top 1% of Isolation Forest anomalies are examined separately.

These transactions may represent unusual combinations of behavioural characteristics that do not exceed any individual SQL rule threshold.
"""

# Identify model-only anomalies
python_only_anomalies = (
    model_results[
        (model_results["risk_level"] == "Low")
        & (model_results["top_1pct_anomaly"] == 1)
    ]
    .sort_values(
        "anomaly_score",
        ascending=False
    )
)

print(
    f"Python-only top 1% anomalies: "
    f"{len(python_only_anomalies):,}"
)

# Review model-only anomalies
python_only_anomalies[
    [
        "SalesOrderID",
        "CustomerID",
        "OrderDate",
        "order_value",
        "days_since_previous_order",
        "prior_order_count",
        "prior_avg_order_value",
        "amount_vs_customer_avg",
        "OnlineOrderFlag",
        "anomaly_score",
        "anomaly_percentile"
    ]
].head(10)

# Select comparison features
comparison_features = [
    "order_value",
    "days_since_previous_order",
    "prior_order_count",
    "prior_avg_order_value",
    "amount_vs_customer_avg"
]

# Select normal low risk
low_risk_normal = model_results[
    (model_results["risk_level"] == "Low")
    & (model_results["top_1pct_anomaly"] == 0)
]

# Compare median profiles
profile_comparison = pd.DataFrame({
    "Python Top 1%": (
        python_only_anomalies[comparison_features]
        .median()
    ),
    "Other Low Risk": (
        low_risk_normal[comparison_features]
        .median()
    )
}).round(2)

profile_comparison

"""### Python-Only Anomaly Findings

- The Python-only anomalies show a distinct behavioural profile rather than an obviously higher-risk transaction pattern.

- Compared with the broader Low-risk population, these transactions are associated with customers who have substantially more purchasing history, lower typical transaction values and shorter intervals between purchases.

- This highlights an important distinction between statistical anomaly detection and transaction-risk detection. Isolation Forest identifies observations that are unusual within the multivariate feature space, but unusual behaviour is not necessarily suspicious behaviour.

- For this reason, the Python anomaly score is treated as a complementary investigation signal rather than a standalone fraud-risk classification.

## 12. Behaviour-Focused Anomaly Model

The initial Isolation Forest model identified statistically unusual customer profiles, including frequent low-value purchasers that were not necessarily transaction-risk concerns.

A second model is therefore evaluated using a narrower set of behavioural features designed to focus more directly on deviations in transaction timing and customer-specific purchasing behaviour.
"""

# Select behavioural features
behaviour_features = [
    "days_since_previous_order",
    "prior_order_count",
    "amount_vs_customer_avg",
    "OnlineOrderFlag"
]

# Create behaviour dataset
X_behaviour = X_model[behaviour_features].copy()

# Log-transform features
X_behaviour["days_since_previous_order"] = np.log1p(
    X_behaviour["days_since_previous_order"]
)

X_behaviour["prior_order_count"] = np.log1p(
    X_behaviour["prior_order_count"]
)

# Scale behaviour features
behaviour_scaler = StandardScaler()

X_behaviour_scaled = behaviour_scaler.fit_transform(
    X_behaviour
)

X_behaviour_scaled = pd.DataFrame(
    X_behaviour_scaled,
    columns=X_behaviour.columns,
    index=X_behaviour.index
)

# Train behaviour model
behaviour_model = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42
)

behaviour_model.fit(X_behaviour_scaled)

# Calculate behaviour scores
model_results["behaviour_anomaly_score"] = (
    -behaviour_model.decision_function(
        X_behaviour_scaled
    )
)

# Rank behaviour anomalies
model_results["behaviour_anomaly_percentile"] = (
    model_results["behaviour_anomaly_score"]
    .rank(pct=True)
)

# Validate high-risk cases
model_results[
    model_results["risk_level"] == "High"
][
    [
        "SalesOrderID",
        "CustomerID",
        "days_since_previous_order",
        "amount_vs_customer_avg",
        "transaction_risk_score",
        "anomaly_percentile",
        "behaviour_anomaly_percentile",
        "risk_reason"
    ]
].sort_values(
    "behaviour_anomaly_percentile",
    ascending=False
)

"""### Behaviour-Focused Model Findings

- The refined behavioural Isolation Forest produces stronger alignment with the SQL risk framework.

- All ten SQL High-risk transactions fall within the top 5% of behavioural anomalies, while three fall within the top 1%.

- The refinement reduces the influence of absolute spending levels and focuses the model more directly on transaction timing, purchasing history and deviations from customer-specific spending behaviour.

- The model is not treated as a fraud classifier. Instead, it provides a complementary statistical prioritisation signal alongside the transparent SQL risk framework.

## 13. Behaviour Model Comparison

The refined anomaly model is compared across SQL risk levels to evaluate how strongly behavioural anomaly rankings concentrate among higher-priority transactions.
"""

# Create behaviour thresholds
model_results["behaviour_top_1pct"] = (
    model_results["behaviour_anomaly_percentile"] >= 0.99
).astype(int)

model_results["behaviour_top_5pct"] = (
    model_results["behaviour_anomaly_percentile"] >= 0.95
).astype(int)

model_results["behaviour_top_10pct"] = (
    model_results["behaviour_anomaly_percentile"] >= 0.90
).astype(int)

# Compare risk levels
behaviour_comparison = (
    model_results
    .groupby("risk_level")
    .agg(
        transactions=("SalesOrderID", "count"),
        avg_behaviour_score=("behaviour_anomaly_score", "mean"),
        top_1pct=("behaviour_top_1pct", "sum"),
        top_5pct=("behaviour_top_5pct", "sum"),
        top_10pct=("behaviour_top_10pct", "sum")
    )
    .round(4)
)

behaviour_comparison

# Calculate overlap rates
behaviour_rates = behaviour_comparison.copy()

behaviour_rates["top_1pct_rate"] = (
    behaviour_rates["top_1pct"]
    / behaviour_rates["transactions"] * 100
).round(2)

behaviour_rates["top_5pct_rate"] = (
    behaviour_rates["top_5pct"]
    / behaviour_rates["transactions"] * 100
).round(2)

behaviour_rates["top_10pct_rate"] = (
    behaviour_rates["top_10pct"]
    / behaviour_rates["transactions"] * 100
).round(2)

behaviour_rates[
    [
        "avg_behaviour_score",
        "top_1pct_rate",
        "top_5pct_rate",
        "top_10pct_rate"
    ]
]

# Plot behaviour overlap
behaviour_rates[
    [
        "top_1pct_rate",
        "top_5pct_rate",
        "top_10pct_rate"
    ]
].plot(
    kind="bar",
    figsize=(10, 5)
)

plt.title("Behavioural Anomaly Concentration by SQL Risk Level")
plt.xlabel("SQL Risk Level")
plt.ylabel("Transactions in Anomaly Group (%)")
plt.xticks(rotation=0)
plt.legend(["Top 1%", "Top 5%", "Top 10%"])

plt.show()

"""# Visualization Dashboard Dataset Export

The final analytical dataset combines the complete SQL transaction population with the behavioural anomaly indicators generated in Python.

Transactions without sufficient customer history are retained in the dataset but identified as not eligible for behavioural anomaly scoring.
"""

# Create Tableau dataset
tableau_df = df.copy()

# Mark model eligibility
tableau_df["model_eligible_flag"] = 0

tableau_df.loc[
    model_results.index,
    "model_eligible_flag"
] = 1

# Add behaviour scores
tableau_df.loc[
    model_results.index,
    "behaviour_anomaly_score"
] = model_results["behaviour_anomaly_score"]

tableau_df.loc[
    model_results.index,
    "behaviour_anomaly_percentile"
] = model_results["behaviour_anomaly_percentile"]

# Add anomaly groups
tableau_df["behaviour_top_1pct"] = 0
tableau_df["behaviour_top_5pct"] = 0
tableau_df["behaviour_top_10pct"] = 0

tableau_df.loc[
    model_results.index,
    "behaviour_top_1pct"
] = model_results["behaviour_top_1pct"]

tableau_df.loc[
    model_results.index,
    "behaviour_top_5pct"
] = model_results["behaviour_top_5pct"]

tableau_df.loc[
    model_results.index,
    "behaviour_top_10pct"
] = model_results["behaviour_top_10pct"]

# Add initial scores
tableau_df.loc[
    model_results.index,
    "anomaly_score"
] = model_results["anomaly_score"]

tableau_df.loc[
    model_results.index,
    "anomaly_percentile"
] = model_results["anomaly_percentile"]

# Validate final dataset
print(f"Total Rows: {tableau_df.shape[0]:,}")
print(f"Total Columns: {tableau_df.shape[1]}")
print(
    f"Model Eligible: "
    f"{tableau_df['model_eligible_flag'].sum():,}"
)

# Review final fields
tableau_df[
    [
        "SalesOrderID",
        "CustomerID",
        "order_value",
        "risk_level",
        "transaction_risk_score",
        "model_eligible_flag",
        "behaviour_anomaly_score",
        "behaviour_anomaly_percentile",
        "behaviour_top_1pct",
        "behaviour_top_5pct",
        "behaviour_top_10pct"
    ]
].head(6)

# Export dataset
tableau_df.to_csv(
    "fraud_analytics_tableau.csv",
    index=False
)

# Confirm export
print(
    f"Exported {len(tableau_df):,} transactions "
    f"for Tableau."
)